cabal-version:      3.0
name:               onelastleaf-plugin-sdk
version:            0.1.0
synopsis:           Official onelastleaf process-plugin SDK for Haskell
description:        A Grapesy-based runtime for trusted onelastleaf plugins.
homepage:           https://github.com/onelastleaf/haskell-plugin-sdk
bug-reports:        https://github.com/onelastleaf/haskell-plugin-sdk/issues
license:            GPL-3.0-only
license-file:       LICENSE
author:             onelastleaf contributors
maintainer:         onelastleaf contributors
category:           Network
build-type:         Simple
tested-with:        GHC == 9.6.7
extra-source-files: README.md
                  , proto/oll/common.proto
                  , proto/oll/config.proto
                  , proto/oll/document.proto
                  , proto/oll/plugin.proto

common language-settings
  default-language: GHC2021
  ghc-options:      -Wall
  default-extensions:
      DataKinds
      DeriveAnyClass
      DerivingStrategies
      DuplicateRecordFields
      ImportQualifiedPost
      LambdaCase
      OverloadedLabels
      OverloadedStrings
      TypeApplications
      TypeFamilies

library internal
  import:          language-settings
  visibility:      private
  hs-source-dirs:  src, generated
  exposed-modules:
      Onelastleaf.PluginSDK.Host
      Onelastleaf.PluginSDK.Internal.Endpoint
      Onelastleaf.PluginSDK.Internal.Protocol
      Onelastleaf.PluginSDK.Internal.Sender
      Onelastleaf.PluginSDK.Runtime
      Onelastleaf.PluginSDK.Types
      Proto.Oll.Common
      Proto.Oll.Config
      Proto.Oll.Document
      Proto.Oll.Plugin
      Proto.Oll.Plugin.API
  other-modules:
      Proto.Oll.Common_Fields
      Proto.Oll.Config_Fields
      Proto.Oll.Document_Fields
      Proto.Oll.Plugin_Fields
  build-depends:
      async                     >= 2.2 && < 2.3
    , base                      >= 4.16 && < 5
    , bytestring                >= 0.10 && < 0.13
    , containers                >= 0.6 && < 0.8
    , cryptohash-sha256         >= 0.11 && < 0.12
    , grapesy                   >= 1.1.1 && < 1.2
    , network                   >= 3.1 && < 3.3
    , proto-lens                >= 0.7 && < 0.8
    , proto-lens-protobuf-types >= 0.7 && < 0.8
    , proto-lens-runtime        >= 0.7 && < 0.8
    , stm                       >= 2.5 && < 2.6
    , text                      >= 1.2 && < 2.2
    , time                      >= 1.9 && < 1.15

library
  import:          language-settings
  hs-source-dirs:  public
  exposed-modules: Onelastleaf.PluginSDK
  reexported-modules:
      Proto.Oll.Common
    , Proto.Oll.Config
    , Proto.Oll.Document
    , Proto.Oll.Plugin
  build-depends:
      base                            >= 4.16 && < 5
    , bytestring                      >= 0.10 && < 0.13
    , containers                      >= 0.6 && < 0.8
    , grapesy                         >= 1.1.1 && < 1.2
    , onelastleaf-plugin-sdk:internal
    , proto-lens                      >= 0.7 && < 0.8
    , text                            >= 1.2 && < 2.2

test-suite unit
  import:         language-settings
  type:           exitcode-stdio-1.0
  hs-source-dirs: test
  main-is:        Main.hs
  build-depends:
      async
    , base
    , grapesy
    , onelastleaf-plugin-sdk
    , onelastleaf-plugin-sdk:internal
    , network
    , proto-lens
    , stm
    , text

source-repository head
  type:     git
  location: https://github.com/onelastleaf/haskell-plugin-sdk.git

executable conformance
  import:         language-settings
  hs-source-dirs: app
  main-is:        Conformance.hs
  build-depends:
      base
    , bytestring
    , containers
    , grapesy
    , onelastleaf-plugin-sdk
    , proto-lens
    , text
